/* Bump the cache stamp.  node tools/stamp.mjs
   Rewrites every ?v= in index.html AND version.txt from one value.
   version.txt on its own is a lie: the ?v= stamps are the real cache key. */
import { readFileSync, writeFileSync, existsSync, copyFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const STAMP = String(Math.floor(Date.now() / 1000));

/* ---------- the shared progress files ----------
   labs-shared/labs.json is the single register of labs — one place for each lab's question
   count, the shelf it sits behind, and the localStorage key it keeps progress under (which is
   NOT always <id>.v2). labs-shared/progress.js is the only code that knows how to read a
   lab's record, so this hub never has to know a lab's internals. Both are copied in here, so
   the published site is self-contained: adding a lab means editing labs.json and rebuilding. */
function findShared(from) {
  let dir = from;
  for (let i = 0; i < 8; i++) {
    if (existsSync(resolve(dir, 'labs-shared/labs.json'))) return resolve(dir, 'labs-shared');
    const up = resolve(dir, '..'); if (up === dir) break; dir = up;
  }
  return null;
}
const SHARED = findShared(REPO);
if (SHARED) {
  mkdirSync(resolve(REPO, 'js/data'), { recursive: true });
  copyFileSync(resolve(SHARED, 'labs.json'), resolve(REPO, 'js/data/labs.json'));
  const reg = readFileSync(resolve(SHARED, 'labs.json'), 'utf8');
  writeFileSync(resolve(REPO, 'js/data/labs.js'),
    '/* GENERATED by tools/stamp.mjs from labs-shared/labs.json — do not edit. */\n' +
    'window.LABS_REGISTER = ' + reg.trim() + ';\n');
  copyFileSync(resolve(SHARED, 'progress.js'), resolve(REPO, 'js/progress.js'));
  /* one Google sign-in for the whole site, the same file every lab copies in */
  copyFileSync(resolve(SHARED, 'signin.js'), resolve(REPO, 'js/signin.js'));
  /* Every lab's stations — ids, names and question counts only, no questions and no answer
     hashes. Built by tools/stations-manifest.mjs. It is the only way anything outside a lab can
     name a station or know how many questions one asks, which is what lets a teacher pick parts
     of a lab to set, and what turns "ileum-villi" into "Small intestine" on the teacher pages.
     Optional: a hub still works without it, it simply cannot name stations. */
  const stations = resolve(SHARED, 'stations.json');
  const haveStations = existsSync(stations);
  if (haveStations) copyFileSync(stations, resolve(REPO, 'js/data/stations.json'));
  console.log('  shared        labs.json + progress.js + signin.js' +
              (haveStations ? ' + stations.json' : ' (no stations.json — run tools/stations-manifest.mjs)') + ' copied in');
} else {
  console.error('  labs-shared/ not found above ' + REPO + ' — progress files not refreshed');
}
/* Every page that carries ?v= stamps, not just the front one — a page left unstamped serves a
   stale stylesheet to anyone who has visited before, which is a bug you only see on someone
   else's machine. index.html must exist and must carry stamps; the rest are stamped if present. */
const PAGES = ['index.html', 'applications.html'];
let n = 0;
for (const page of PAGES) {
  const f = resolve(REPO, page);
  if (!existsSync(f)) {
    if (page === 'index.html') { console.error('index.html is missing'); process.exit(1); }
    continue;
  }
  const html = readFileSync(f, 'utf8');
  const hits = (html.match(/\?v=\d+/g) || []).length;
  if (!hits) {
    if (page === 'index.html') { console.error('index.html carries no ?v= stamps'); process.exit(1); }
    console.error('  ' + page + ' carries no ?v= stamps — nothing to stamp');
    continue;
  }
  writeFileSync(f, html.replace(/\?v=\d+/g, '?v=' + STAMP));
  n += hits;
}
writeFileSync(resolve(REPO, 'version.txt'), STAMP + '\n');
console.log('stamped ' + n + ' assets and version.txt with ' + STAMP);
